### PR TITLE
Mac setup

### PR DESCRIPTION
**Pull request by jaenrig-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Changes:

* Modified  "mpy-psoc6.py" script for macOS support
* Minor improvements in "mpy-psoc6.py" script user experience (notified waiting restart)
* "mpy-psoc6.py" script uses now openocd v5
* Removed "quick-start" command from "mpy-psoc6.py"
* Removed OS specific scripts for Win and Linux
* Updates in installation and getting started psoc6 docs with mentioned changes.

Reviewers please:
- Check if the script still working in your machines --> https://github.com/Infineon/micropython/blob/mac-setup/tools/psoc6/mpy-psoc6.py (remember if you are in WSL to avoid the kitprog3 firmware update with the *-s* flag)
- You can review the docs in the corresponding rtd version:
https://ifx-micropython.readthedocs.io/en/mac-setup/psoc6/intro.html --> ⚠️ Remember the url of the curl command still points to the main branch. So modify the url or download the mpy-psoc6.py script manually for testing.
https://ifx-micropython.readthedocs.io/en/mac-setup/psoc6/installation.html

### CODE REVIEW

**Review by NikhitaR-IFX — APPROVED** [review]
I don't understand much without trying it out. So I will approve and trust your experiments on MAC for the working :)
- I tried from cmd prompt the script and can confirm it does not break anything existing.
- Feedback: 
image
Here I would prefer to see the version number rather than "latest". Or maybe both "version number (latest)" is fine. 
- By the way, additionally one question, is it supposed to be the following print statements:
image

I think "Firmware hello-world deployed successfully" followed by "Firmware mpy-psoc6 deployed successfully" is bit confusing. Maybe @ederjc  is a better test object here to comment.

**Review by IFX-Anusha — APPROVED** [review]

**Comment by IFX-Anusha** [comment]
> I don't understand much without trying it out. So I will approve and trust your experiments on MAC for the working :)
> 
> * I tried from cmd prompt the script and can confirm it does not break anything existing.
> * Feedback:
>   image
>   Here I would prefer to see the version number rather than "latest". Or maybe both "version number (latest)" is fine.
> * By the way, the following print statements is in intended order? :
>   image
> 
> I think "Firmware hello-world deployed successfully" followed by "Firmware mpy-psoc6 deployed successfully" is bit confusing. Maybe @ederjc is a better test object here to comment.

I would also prefer the version number rather than the latest

**Comment by ederjc** [comment]
I tested it - looks good for me 👍 
Can we make device-setup the default option when called without parameters? Then this could be started by double-clicking also

**Comment by jaenrig-ifx** [comment]
@ederjc I need to the check the argparse lib options for default subparsers. 

An alternative would be that the script finds out if it has been called by the command line or by clicking. And that seems more or less trivial for one OS but hard to maintain cross platform. 

The clickable option was dropped with the OS dedicated scripts removal. We can add a ticket for this click default option. I think there should be an easy (to maintain) way. But I will close now this one.

**Comment by ederjc** [comment]
@jaenrig-ifx Yes, this "double clicking" thought is not urgent and should not block this merge.
It can be considered during the next change of the script.

**Pull request merged**
