### PR TITLE
tools/psoc6/mpy-psoc6.py: Adding AI kit.

### PR DESCRIPTION
**Pull request by NikhitaR-IFX**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Enabled AI Kit in flasher script to allow flashing.

**Test**: Generated locally .hex and hardcoded in the script the path to test and works fine.

*This is a draft and urls will be tested once the binary is generated and available as part release.

### CODE REVIEW

**Review by jaenrig-ifx — COMMENTED** [review]
Looks good @NikhitaR-IFX! 
Then we need to add the message to wait for the LED to blink for completion. 
Later we will need to add the new erase binaries to the newer release (still not existing). 
We can tomorrow try to make an intermediate release from this branch, and see how well it works. 

As we are adding new files, and new fixed version from which retrieve the erase bins, we have to coordinate well the merge of the ai-kit branch with the main, and the addition of those files. Otherwise, any new user of the script will experience some malfunctioning.

In future we will try to avoid this release mess complexity with the openocd erase approach...

**Comment by NikhitaR-IFX** [comment]
> Looks good @NikhitaR-IFX! Then we need to add the message to wait for the LED to blink for erase completion in device-erase (which should also be doable for this new kit). Later we will need to add the new erase binaries to the newer release (still not existing). We can tomorrow try to make an intermediate release from this branch, and see how well it works.
> 
> As we are adding new files, and new fixed version from which retrieve the erase bins, we have to coordinate well the merge of the ai-kit branch with the main, and the addition of those files. Otherwise, any new user of the script will experience some malfunctioning.
> 
> In future we will try to avoid this release mess complexity with the openocd erase approach...

Yes that would be nice if we can make an intermediate release and check if this works fine

**Comment by jaenrig-ifx** [comment]
@NikhitaR-IFX I have created a pre-release with all require files.
https://github.com/Infineon/micropython/releases/tag/v0.10.0

I have tried the following commands both in WSL and Windows:
`python mpy-psoc6.py device-setup -s -b **_board_** -v v0.10.0` (adding -s in case of WSL)
`python mpy-psoc6.py device-erase -b **_board_**`
for all 3 boards and this latest script.
All working fine :) 

Remember we have to specify the version because the "latest" is still pointing to the v0.9.0 (as this is only a pre-release).

One thing we have to try is a new virgin AI kit board. Because we have not created the corresponding hello-world for that one, and it is just skipping that step.

**Review by jaenrig-ifx — APPROVED** [review]

**Comment by NikhitaR-IFX** [comment]
> @NikhitaR-IFX I have created a pre-release with all require files. https://github.com/Infineon/micropython/releases/tag/v0.10.0
> 
> I have tried the following commands both in WSL and Windows: `python mpy-psoc6.py device-setup -s -b <board> -v v0.10.0` (adding -s in case of WSL) `python mpy-psoc6.py device-erase -b <board>` for all 3 boards and this latest script. All working fine :)
> 
> Remember we have to specify the version because the "latest" is still pointing to the v0.9.0 (as this is only a pre-release).
> 
> One thing we have to try is a new virgin AI kit board. Because we have not created the corresponding hello-world for that one, and it is just skipping that step.
> 
> Please, @IFX-Anusha and @ramya-subramanyam review as well, and try out [the script](https://github.com/Infineon/micropython/blob/enable-flasher-script/tools/psoc6/mpy-psoc6.py) against different boards.

Thanks @jaenrig-ifx! I have a new kit with me where nothing is flashed from my end so far. I will try there and confirm.

**Pull request merged**
