### PR TITLE
Fix external flash fat fs

### PR DESCRIPTION
**Pull request by ramya-subramanyam**

### CODE REVIEW

**Comment by jaenrig-ifx** [comment]
How shall we test it? 
Building with FAT instead of LFS2?

**Comment by ramya-subramanyam** [comment]
> How shall we test it? Building with FAT instead of LFS2?

Yes, you need to remove the define MICROPY_VFS_LFS2 and set MICROPY_VFS_FAT in mpconfigport.mk and build

**Comment by ramya-subramanyam** [comment]
> How shall we test it? Building with FAT instead of LFS2?

image

**Comment by jaenrig-ifx** [comment]
Yep, it works on 062-4343W:
image
For the BLE board it does not work:
image

**Comment by jaenrig-ifx** [comment]
image
Works now :)

**Review by jaenrig-ifx — APPROVED** [review]

**Review by NikhitaR-IFX — APPROVED** [review]
Also works for me!

**Review by IFX-Anusha — APPROVED** [review]
I checked with Proto Kit and it works ! I don't have a BLE board now to test

**Pull request merged**
