### PR TITLE
Main i2s merge

### PR DESCRIPTION
**Pull request by IFX-Anusha**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
I2S Blocking Mode implementation.

### CODE REVIEW

**Review by jaenrig-ifx — APPROVED** [review]
👏

**Comment by jaenrig-ifx** [comment]
@IFX-Anusha please, add also the test that you have developed under test/psoc6/dut.

**Comment by IFX-Anusha** [comment]
> @IFX-Anusha please, add also the test that you have developed under test/psoc6/dut.

@jaenrig-ifx . I can add the test but that will not work here since rx is also configured as a master here( Since that's how it will work in the case of a microphone). Should I change that into rx slave & add the test? Or Just I add the test there?

**Comment by jaenrig-ifx** [comment]
We will rework the test to be functional in a ci/cd setup. Don´t worry.
we should not care about any microphone, it will be lastly check if the protocol and peripheral is working, despite the source and destination of the i2s frames.

**Pull request merged**
