### PR TITLE
New python mpy-psoc6 script and  kitprog check install option

### PR DESCRIPTION
**Pull request by jaenrig-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

* Added python mpy-psoc6.py utility script replacing native options
* Added kitprog update option to device-setup
* Coloring output success, errors and user interaction requests
* Extended command help
* Handling error message from fw-loader and openocd (usually happening when the boards are not connected)
* Updated installation documentation --> https://ifx-micropython.readthedocs.io/en/add-kitprog-check-install-script/psoc6/installation.html

### CODE REVIEW

**Review by IFX-Anusha — APPROVED** [review]
Nice  ! It works 🚀 !! coloring is 🤩

**Comment by jaenrig-ifx** [comment]
😃 Only, if you try in WSL the update option (by default) in quick-start or device-setup -u, it will disconnect from the wsl, and should fail...
Nothing like that should be happening in a "normal" linux setup.

**Review by NikhitaR-IFX — APPROVED** [review]
Checked again and works for me too! 🙌

**Comment by jaenrig-ifx** [comment]
@NikhitaR-IFX done with the rebasing :)

**Pull request merged**
